import laddersJson from './ladders.json';

export type RigId =
	| 'idle'
	| 'eco'
	| 'standard'
	| 'boost'
	| 'overclock'
	| 'nitro'
	| 'furnace'
	| 'inferno'
	| 'meltdown'
	| 'reactor'
	| 'plasma';

export type RigInfo = {
	id: RigId;
	name: string;
	targetTemp: number;
	flavor: string;
};

// dense ladder so the shutdown-temp dial feels like a custom multiplier
export const RIGS: RigInfo[] = [
	{ id: 'idle', name: 'IDLE', targetTemp: 1.2, flavor: 'barely warm. basically a savings account.' },
	{ id: 'eco', name: 'ECO', targetTemp: 1.5, flavor: 'undervolted. boring. pays the rent.' },
	{ id: 'standard', name: 'STANDARD', targetTemp: 2, flavor: 'stock cooler, stock nerves.' },
	{ id: 'boost', name: 'BOOST', targetTemp: 3, flavor: 'factory overclock. mild sweat.' },
	{ id: 'overclock', name: 'OVERCLOCK', targetTemp: 5, flavor: 'warranty void. thermal paste optional.' },
	{ id: 'nitro', name: 'NITRO', targetTemp: 7, flavor: 'aftermarket fans, screaming.' },
	{ id: 'furnace', name: 'FURNACE', targetTemp: 10, flavor: 'heats the room. sometimes the house.' },
	{ id: 'inferno', name: 'INFERNO', targetTemp: 15, flavor: 'the smoke detector is unplugged.' },
	{ id: 'meltdown', name: 'MELTDOWN', targetTemp: 25, flavor: 'silicon roulette. bring a fire blanket.' },
	{ id: 'reactor', name: 'REACTOR', targetTemp: 50, flavor: 'unlicensed fission. tell no one.' },
	{ id: 'plasma', name: 'PLASMA', targetTemp: 100, flavor: 'this is not mining. this is a star.' },
];

export const RIG_MAP: Record<RigId, RigInfo> = Object.fromEntries(
	RIGS.map((rig) => [rig.id, rig]),
) as Record<RigId, RigInfo>;

// must match tools/gen_overheat_math.py (checkpoint-banking distribution)
export const RTP = 0.965;

export type WinTier = 'clean' | 'overdrive' | 'critical' | 'golden';

export type LadderRung = {
	/** temperature the rung sits at (multiplier) */
	temp: number;
	/** cumulative payout secured once the rung is crossed (x stake) */
	bank: number;
	/** probability the round fries between this rung and the next */
	prob: number;
};

export type LadderTier = {
	tier: WinTier;
	/** payout x stake (target x 1 / 1.5 / 3 / 10) */
	payout: number;
	prob: number;
};

export type RigLadder = {
	target: number;
	profile: 'drip' | 'balanced' | 'spike' | 'spike_deep';
	rungs: LadderRung[];
	tiers: LadderTier[];
	bustProb: number;
	anyPayoutProb: number;
	profitProb: number;
	maxWin: number;
	std: number;
};

/** Per-rig checkpoint ladders, generated by tools/gen_overheat_math.py. */
export const LADDERS = laddersJson as Record<RigId, RigLadder>;

export const ladderOf = (rigId: RigId): RigLadder => LADDERS[rigId];

/** cumulative amount secured at a given display temperature (x stake) */
export const securedAtTemp = (rigId: RigId, temp: number): number => {
	const ladder = LADDERS[rigId];
	let secured = 0;
	for (const rung of ladder.rungs) {
		if (temp >= rung.temp - 1e-9) secured = rung.bank;
		else break;
	}
	return secured;
};

/** max win per rig = golden tier = 10x the shutdown target */
export const MAX_WIN_MULT = 10;

// terminal palette (brief 5.3)
export const COLORS = {
	bg: '#0a0e0a',
	green: '#00ff41',
	amber: '#ffb000',
	red: '#ff2b2b',
};

// book event amounts are payout multiplier x 100 (matches math generator)
export const BOOK_AMOUNT_SCALE = 100;

export const MAX_LOG_LINES = 14;
